version: "3"

services:
  db:
    image: postgres
    environment:
      # Changing these variables will not affect an existing volume.
      # Remove the existing volume first and re-run compose to apply changes.
      POSTGRES_USER: historead
      POSTGRES_PASSWORD: password
      POSTGRES_DB: historead
    networks:
      - backend
    volumes:
      - "pg-data:/var/lib/postgresql/data"

  backend:
    image: historead-backend
    depends_on:
      - db
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - backend
      - webnet
    ports:
      - "8000:80"
    volumes:
      # Map the host src directory to container src directory.
      # Run `docker-compose restart backend` to pick up local file changes.
      # This is only appropriate in a dev environment.
      # Note: Find a sustainable strategy for this (like multiple yml files)
      - ./backend/migrations:/usr/app/migrations
      - ./backend/seeds:/usr/app/seeds
      - ./backend/src:/usr/app/src

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet

volumes:
  pg-data:

networks:
  backend:
  webnet:
